 
name:Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级 checkout 到最新
        with:
          submodules: recursive

      - name: Set up Android NDK
        uses: android-actions/setup-android-ndk@v1
        with:
          ndk-version: r25b

      - name: Configure NDK Path
        run: echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Build project
        run: |
          mkdir build && cd build
          cmake -DNDK_PATH=${{ env.ANDROID_NDK_HOME }} ..
          make

      - name: Generate Magisk Module
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 使用 v4
        with:
          name: zygisk-il2cppdumper
          path: zygisk-il2cppdumper.zip  # 确保路径正确
 
